import 'dart:convert';
import 'dart:typed_data';

/// Perintah raster ESC/POS ('GS v 0') logo resmi Bank Sampah eRWe TeluLas,
/// SUDAH dikonversi monokrom (dithering) & di-precompute sekali dari
/// gambar asli - jadi saat cetak tinggal decode base64 lalu kirim
/// langsung ke printer, TANPA perlu library image-processing tambahan
/// di Flutter. Lebar cetak: 160 dot (~30mm @ 58mm paper) - proporsional,
/// tidak mendominasi struk seperti versi 280 dot sebelumnya.
const String kLogoRasterBase64 =
    'HXYwABQAnQAAAAAAAAAAAALf/UAAAAAAAAAAAAAAAAAAAAAAfSACvQAAAAAAAAAAAAAAAAAAAAuAAAAC4AAAAAAAAAAAAAAAAAAA' 
    'dAAAAAAeAAAAAAAAAAAAAAAAAAOAAAAAAAHAAAAAAAAAAAAAAAAAHAAAAAAAADgAAAAAAAAAAAAAAADgAAAJIAAABgAAAAAAAAAA' 
    'AAAAAwAAC///0AABwAAAAAAAAAAAAAAMAAF/d99/QAAwAAAAAAAAAAAAADAAF/3dd/3wABgAAAAAAAAAAAAAwAD/1AAAF78ABwAA' 
    'AAAAAAAAAAEAB7oAAAAA98AAgAAAAAAAAAAABgAd6AAAAAAO+ABgAAAAAAAAAAAIAHcAAAAAAAHeADAAAAAAAAAAADAD/AAAAAAA' 
    'ADuADAAAAAAAAAAAQAugAAAAAAAAD+ACAAAAAAAAAAGAHsAAAAAAAAAC+AGAAAAAAAAAAgB7AAAAAAAAAADcAMAAAAAAAAAEAdwA' 
    'AAAAAAAAAD8AIAAAAAAAAAgC8AAAAAAAAAAAC8AYAAAAAAAAMA/AAAAAAAAAAAAH4AgAAAAAAABAFwAAAAAAAAAAAACwBgAAAAAA' 
    'AIA9AAAAAAAAAAAAAPwDAAAAAAABAOwAAAAAAAAAAAAANgCAAAAAAAIA8AAAAAAAAAAAAAAfAMAAAAAABAOgAAAAAAAAAAAAAAeA' 
    'IAAAAAAIB8AAAAAAAAAAAAAAAuAwAAAAAAgNAAAAAAAAAAAAAAAB4BAAAAAAEB8AAAAAAAAAAAAAAADYDAAAAAAgNAAAAAAAAAAA' 
    'AAAAAHgEAAAAAEB8AAAAAAAAAAAAAAAALgIAAAAAwNgAAAAAAAAAAAAAAAAeAQAAAAEA8AAAAAAAAAAAAAAAAAsBgAAAAQHAAAAA' 
    'AAAAAAAAAAAAB4CAAAACA8AAkAABgAgAAAAAGAADwEAAAAQGgAD8AAGAPwAAAAAYAAFgYAAABAeAANYAAYA2AAAAABgAAeAgAAAI' 
    'DgAAxjCRmGAYSIkFGgAAcBAAABAeAADM+fmYOH7/z8+fgAB4CAAAEDgAAPwM3bA8Jmzs4NGAACgIAAAgPAAA1C2JYA8MxkxFmYAA' 
    'PAQAACBoAADG/I3wAzpkZO/ZgAAeBgAAQPAAAMbN2bADZs7MSJiAAAoCAADAsAAA1pSMmHtmZG7t2cAADwIAAIHgAAD8/c2YPj5O' 
    'a8+ZgAAHgQAAgcAAAAAgCIgAIEBNBAAACAKBgAEDQAAAAAAAAAAAAAwAAAAwA8CAAwOAAAAAAAAAAAAADAAAAKgBwEACBoAAAAAA' 
    'AAAAAAAAAAACqAFAQAIHAAAAAAAAAAAAAAAAAAWoAOBABAcAAAAAAAAAAAAAAAAAGrQA4CAEDQAAAAAAAAAAAAAAAAAq1ABwIAQO' 
    'AAAABEAAAABAAQAAACtUAHAwCBwAAAAH/+A/AfgH4AAAbVgAWBAIHAAAAA+/+D8A2AdgAACq1AA4EBAYAAAABu1+NwH8D8AAALVY' 
    'ADgIEDwAAAAH/9odgWgKwAABVtQAHAgQMAAAAA1V/x8B/A/AAADbaAAYCBA4AAAAB+AtG4G0DYAAAWq4AB4IIHAAB+AHQD8eg/wP' 
    'gH4BV6gADAQgcAAdvA3gNY+DXh2B+4Da0AAeBCBwADf8B8AfG4P0F4OvwW1wAAoEINAAftcGwDsOw34eh/3gt6AADgRAYADbfg/g' 
    'Lw3H1hsO73DawAAHBkDgAPwbhUB9B8NfHw+B0F8AAAYCQOAA2B8H6u8Ox9o7HYHwagAABwJA4AHwDY9/+gfGnx8fAXgoAJQHAkDA' 
    'AbhPhdtcBWeXNhtE2EBfaAUCQeAB7/uH//AH7Z0+P//wwWSoB4KAwAG/vo61sAOnj7YVu7iCtrADAkHAAfb3x+/wA+8NfD/++IVV' 
    'qAeBgUAB260GwVgDbY+uHVWpC2qwAoOBwAH4AA/B+AP/Bvw3AAENrVADgYHAAagABWHcAasP1B+AABVW0AOBgUAA/AQHwPYD/gV8' 
    'GoBAHbVgAwGBwAD2Dw9gvgFvB/gP4eAq20ADgYHAAN/9hcBqAfoFrA3/cD1VgAOBgcAAe3cH4H8ArgP4B1vYK+6AAoGBwAAv3g7A' 
    'N4H8A2gD/uB+tQADgYGAAB34B8A+gPYD+AG3gJfcAAOBgcAAA1AEoAqATAKQAFwBguAAA4OBwAAAAAAAAAAAAAAAAAIAAAACgYHA' 
    'AAAAAAAAAAAAAAAABgAAAAOBwcAAAAAAAAAAAAAAAAAAAAAAA4NBQAAAAAAAAAAAAAAAAAAAAAAHAYHgAAAAAAAAAAAAAAAAAAAA' 
    'AAOCQMAAAAKqoADwAAKAAAAAAAAABoJB4AAAA//gAPAAA8AAAAAAAAADAkCgAAAD/+AA8AADwAAAAAAAAAcCQOAAAAP/4ADwAAfA' 
    'AAAAAAAABwJA4AAAAD4AAPAAA8AAAAAAAAAHAkCgAAAAPAOg8UFDwAOgHQAAAA0CIHAAAAA+D/Dx4ePAD/B/gAAABgQg8AAAABwf' 
    '+PHh48Af+P+AAAAOBCBQAAAAPh548ePnwB7484AAAA4EIHAAAAA8PDzx4ePACHzwAAAADgQgOAAAAB48PPHh48AAePgAAAAcDBA4' 
    'AAAAPD/88eHjwAf8/gAAABwIEDQAAAA+P/zx4+PAH/h/gAAAFAgQOAAAABw+1PHhx8AefB/AAAA8CAgcAAAAPjwA8eHjwDw8B8AA' 
    'ADgQCBQAAAA8PgDx8+PCPHhDwAAAKBAIHgAAAB4fuPn/4/+//PfAAAB4EAQOAAAAPA/8+P/j/5/9/4AAAHAgBAsAAAA+B/h8/ef/' 
    'n7j/AAAAYCAGBwAAAAQBQCgoAJIFCBQAAADgIAIGgAAAAAAAAAAAAAAAAAAAAOBAAgOAAAAAAAAAAAAAAAAAAAABwEABA4AAAAAA' 
    'AAAAAAAAAAAAAAHAwAEDQAAAAAAAAAAAAAAAAAAAA4CAAQHgAqqqqqqqqttVVVVVqqADgQAAgMAAAAAAAAAAAAAAAAAAAAcBAADA' 
    '8AAAAAAAAAAAAAAAAAAADQMAAEBwAAAAAAAAAAAAAAAAAAAOAgAAIHgAAQAgAAEAAABAAAQAABoEAAAgKAABQCAAAoAAAFAABAAA' 
    'HAQAABA8AAFMwswCWFGAkzVlAAA4DAAAEB4AAVMoIgKmSkBUxBFAAHgQAAAICwABVCMaYpJSjFUCxUAA0BAAAAwHAAFRKogCokoA' 
    'lFIVAADwMAAABAeAAQzKSgJZkYBDImFAAaAgAAACAsAAAAAAAAAAAAAEAAADwEAAAAMB4AAAAAAAAAAAAAQAAAaAwAAAAQDgAAAA' 
    'AAAAAAAAAAAAD4CAAAAAgLgAAAAAAAAAAAAAAAAKAQAAAABAeAAAAAAAAAAAAAAAAD4CAAAAAGAuAAAcAAOAAA4AoAAAOAYAAAAA' 
    'IB4AAACIQklkgEUoAADoBAAAAAAYC4AAEVCilUqMVKgAAPAYAAAAAAgHgAAZKCJVKgUkoAADoBAAAAAABALgAAEQoFFIiFSIAAbA' 
    'IAAAAAACAfAAEUCjVSqFUKgAD4BAAAAAAAEAeAAAEAAAAAIAAAAaAMAAAAAAAYAuAAAAAAAAAAAAAHwBAAAAAAAAQB8AAAAAAAAA' 
    'AAAA9AMAAAAAAAAwDcAAAAAAAAAAAAOwBAAAAAAAABAD4AAAAAAAAAAABsAYAAAAAAAADAF4AAAAAAAAAAAfgCAAAAAAAAAGANwA' 
    'AAAAAAAAAHoAYAAAAAAAAAEAN4AAAAAAAAAB3ACAAAAAAAAAAMAPwAAAAAAAAAdwAwAAAAAAAAAAYAN4AAAAAAAAHcAEAAAAAAAA' 
    'AAAYAP4AAAAAAAD/ABgAAAAAAAAAAAwAN8AAAAAAB7QAMAAAAAAAAAAAAwAP+gAAAAA66ADAAAAAAAAAAAABgAF/oAAAA++AAYAA' 
    'AAAAAAAAAABgAFr9QAK+/AAGAAAAAAAAAAAAABgAD9////ugABgAAAAAAAAAAAAABgAAd3/93gAAYAAAAAAAAAAAAAABwAAC1Vag' 
    'AAOAAAAAAAAAAAAAAABoAAAAgAAAFgAAAAAAAAAAAAAAABYAAAAAAAB4AAAAAAAAAAAAAAAAA6AAAAAAA4AAAAAAAAAAAAAAAAAA' 
    'WAAAAAA8AAAAAAAAAAAAAAAAAAAH0AAABcAAAAAAAAAAAAAAAAAAAAA/VVX6AAAAAAAAAAAAAAAAAAAAAAC/ugAAAAAAAAAAAA==';

Uint8List get logoRasterBytes => base64Decode(kLogoRasterBase64);
